spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/user;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: admin
    password:
    driverClassName: org.h2.Driver
  liquibase:
    drop-first: true
    change-log: "classpath:liquibase/master-changelog.xml"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: validate
      show-sql: true

